### ISSUE TITLE
智能合约库合约原创问题

### ISSUE THREAD

**Issue by CN-ZHANGYH** [WeBankBlockchain/SmartDev-Contract#171]
![849e11e94fb3927033f14c2d2636d2b](https://github.com/WeBankBlockchain/SmartDev-Contract/assets/84267606/61f036fc-9bb1-42fb-839b-9e5364cb0eea)
![a2b55c26e1c26faa2283d042696955c](https://github.com/WeBankBlockchain/SmartDev-Contract/assets/84267606/203d9bfc-6ae0-4776-b71e-eba226e9f248)

该合约存在可能不是原创，当前提交的合约是所属全国职业技能大赛的模块三的智能合约开发原题以及原文件

**Comment by dalaocu** [comment]
我们核实下，谢谢提供信息~~

**Comment by dalaocu** [comment]
感谢提供信息.
已删除涉及的代码:https://github.com/WeBankBlockchain/SmartDev-Contract/commit/54993bd7673f33ad644a1c6b810499610a82e777
