### ISSUE TITLE
溯源合约改变商品状态时账户地址不准确

### ISSUE THREAD

**Issue by yekai1003** [WeBankBlockchain/SmartDev-Contract#45]
TraceabilityFactory合约的changeTraceGoods函数可以完成商品状态变更，变更时正常要记录变更人的地址，时间戳，状态值，描述，在实际执行代码如下：
`
//Change product status
    function changeTraceGoods(bytes32  goodsGroup, uint64 goodsId, int16 goodsStatus, string memory remark)public{
         Traceability category = getTraceability(goodsGroup);
         category.changeGoodsStatus(goodsId, goodsStatus, remark);
    }
`
最终会触发Goods合约的方法调用，代码如下。
`
function changeStatus(int16 goodsStatus, string memory remark) public {
        _status = goodsStatus;
         _traceData.push(TraceData({addr:msg.sender, status:goodsStatus, timestamp:now, remark:remark}));
          emit newStatus(msg.sender, goodsStatus, now, remark);
    }
`
由于msg.sender在跨合约调用时会变成合约地址，因此最终记录都变成了Traceability合约的地址，这与目标不一致。

**Comment by dalaocu** [comment]
确实存在这个问题，记录的合约地址一直都是Traceability合约的地址。可以加一个address参数传递进来。
在联盟链中，使用tx.origin也是一个可供考虑的选择。

供 @fengqiao 参考。

**Comment by dalaocu** [comment]
#38 fixed
