### ISSUE TITLE
票据合约编译失败

### ISSUE THREAD

**Issue by dalaocu** [WeBankBlockchain/SmartDev-Contract#56]
票据合约编译失败。
![3bd2dde8ab8fe81ea7b35ddfc8c3cbf](https://user-images.githubusercontent.com/20871639/130750713-7912da72-c051-432f-a6e4-f855d1ec63a6.png)

![c5f46017fc13b7daeb9139868851598](https://user-images.githubusercontent.com/20871639/130750800-16b738a8-faaa-466d-92ef-491d385d9f1f.png)
 这里注释需补充信息，否则编译器会报错。

**Comment by hongfish** [comment]
已修改注释

**Comment by dalaocu** [comment]
https://github.com/WeBankBlockchain/SmartDev-Contract/pull/59
